var html_day01 = [
  ['h', "['hɛdɚ]", 1, '标题；h1 ~ h6', 'header'],
  ['p', "['pærəɡræf]", 1, '段落', 'paragraph'],
  ['div', "[də'vɪʒən]", 1, '分配，分隔；', 'division'],
  ['span', '[spæn]', 1, '跨度范围', 'span'],
  ['img', "['ɪmɪdʒ]", 2, '图像，插入图片;', 'image'],
  ['src', '-', 3, '地址', '-'],
  ['a', "['æŋkɚ]", 1, '锚链接', 'anchor'],
  ['href', '-', 3, '超链接', ''],
  ['alt', '[ælt]', 3, '替换文本', ''],
  ['title', "['taɪtl]", 3, '提示文本', ''],
  ['strong', '[strɔŋ]', 1, '强调文本', ''],
  ['video', '[ˈvɪdiəʊ] ', 1, '视频标签', ''],
  ['audio', '[ˈɔːdiəʊ]', 1, '音频标签', ''],
  ['autoplay', '[ˈɔːtəʊ] [pleɪ]', 5, '自动播放', '属性和值一致'],
  ['loop', '[luːp]', 5, '循环播放', '属性和值一致'],
  ['muted', '[ˈmjuːtɪd]', 5, '静音播放', '属性和值一致'],
]

var html_day02 = [
  ['table', "['tebl]", 1, '表格', ''],
  ['tbody', "[ti] ['bɑdi]", 1, '表格主体', ''],
  ['thead', '[ti] [hɛd]', 1, '表格头部', ''],
  ['tr', '-', 1, '行', 'table row'],
  ['th', '-', 1, '表头单元格', 'table head'],
  ['td', '-', 1, '单元格', 'table data'],
  ['ul', "[,ju 'ɛl]", 1, '无序的列表', 'unordered list'],
  ['li', "[lɪst] ['aɪtəm]", 1, '列表项', 'list item'],
  ['input', "['ɪn'pʊt]", 2, '输入，表单控件'],
  ['placeholder', '[ˈpleɪshəʊldə(r)]', 5, '占位符', 'input的提示文本'],
  ['type', '[taɪp]', 3, '类型'],
  ['name', '[nem]', 3, '名称'],
  ['value', "['vælju]", 3, '价值，值；'],
  ['text', '[tɛkst]', 4, '文本'],
  ['password', 4, '[ˈpæsˌwə:d]', '密码'],
  ['radio', "['redɪo]", 4, '收音机，单选按钮；'],
  ['checkbox', "['tʃɛkbɑks]", 4, '复选框'],
  ['submit', "[səb'mɪt]", 4, '提交'],
  ['multiple', '[ˈmʌltɪpl]', 5, '多选文件提交', 'input的file标签属性'],
  ['checked', '[tʃɛkt]', 5, '选中的'],
  ['select', '[sɪˈlekt]', 1, '下拉菜单'],
  ['option', '[ˈɒpʃn]', 1, '下拉菜单选项'],
  ['selected', '[sɪˈlektɪd]', 4, '下拉菜单选择项'],
  ['form', '[fɔrm]', 1, '表单域'],
  ['textarea', '[tekst][ˈeəriə]', 1, '文本域'],
  ['header', '[ˈhedə(r)]', 1, '头部标签', '块元素'],
  ['footer', '[ˈfʊtə(r)]', 1, '尾部标签', '块元素'],

]